// <auto-generated />
namespace Socio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addroleandfriends : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addroleandfriends));
        
        string IMigrationMetadata.Id
        {
            get { return "201711261407090_add-role-and-friends"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
